version: '3.8'
services:
  app:
    image: phptest:latest
    volumes:
      - ./myapp:/www/html/
    ports:
      - 8000:80
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=testdb
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=admin
    ports:
      - 8090:80
    depends_on:
      - mysql